# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainModuleClient extends SpacetimeDBClient

const Types = preload('res://spacetime_bindings/schema/module_main_types.gd')

const Lobby = Types.Lobby
const Message = Types.Message
const Damage = Types.Damage
const User = Types.User
const UserData = Types.UserData

const reducers = preload('res://spacetime_bindings/schema/module_main_reducers.gd')
var db: MainModuleDb

func _init() -> void:
	set_meta("module_name", "Main")
	name = "MainModule"

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_main_db.gd').new(p_local_db)
