# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainModuleDb extends RefCounted

const table_names := ["lobby", "user", "user_data", "user_next"]

var lobby: MainLobbyTable
var user: MainUserTable
var user_data: MainUserDataTable
var user_next: MainUserNextTable

func _init(p_local_db: LocalDatabase) -> void:
	lobby = preload('res://spacetime_bindings/schema/tables/main_lobby_table.gd').new(p_local_db)
	user = preload('res://spacetime_bindings/schema/tables/main_user_table.gd').new(p_local_db)
	user_data = preload('res://spacetime_bindings/schema/tables/main_user_data_table.gd').new(p_local_db)
	user_next = preload('res://spacetime_bindings/schema/tables/main_user_next_table.gd').new(p_local_db)
