# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

const Lobby = preload('res://spacetime_bindings/schema/types/main_lobby.gd')
const Message = preload('res://spacetime_bindings/schema/types/main_message.gd')
const Damage = preload('res://spacetime_bindings/schema/types/main_damage.gd')
const User = preload('res://spacetime_bindings/schema/types/main_user.gd')
const UserData = preload('res://spacetime_bindings/schema/types/main_user_data.gd')
