# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


static func change_color_random(cb: Callable = func(_t: TransactionUpdateMessage): pass) -> void:
	var __id__: int = SpacetimeDB.Main.call_reducer('change_color_random', [], [])
	var __result__ = await SpacetimeDB.Main.wait_for_reducer_response(__id__)
	cb.call(__result__)

## 0. new_input: Vector2 [br]
## 1. global_position: Vector3 [br]
static func move_user(new_input: Vector2, global_position: Vector3, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> void:
	var __id__: int = SpacetimeDB.Main.call_reducer('move_user', [new_input, global_position], [&'Vector2', &'Vector3'])
	var __result__ = await SpacetimeDB.Main.wait_for_reducer_response(__id__)
	cb.call(__result__)

## 0. bytes: Array of int [br]
static func save_my_bytes(bytes: Array[int], cb: Callable = func(_t: TransactionUpdateMessage): pass) -> void:
	var __id__: int = SpacetimeDB.Main.call_reducer('save_my_bytes', [bytes], [&'u8'])
	var __result__ = await SpacetimeDB.Main.wait_for_reducer_response(__id__)
	cb.call(__result__)

## 0. option: Option of String [br]
static func test_option_single(option: Option, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> void:
	var __id__: int = SpacetimeDB.Main.call_reducer('test_option_single', [option], [&'string'])
	var __result__ = await SpacetimeDB.Main.wait_for_reducer_response(__id__)
	cb.call(__result__)

## 0. option: Option of Array of String [br]
static func test_option_vec(option: Option, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> void:
	var __id__: int = SpacetimeDB.Main.call_reducer('test_option_vec', [option], [&'vec_string'])
	var __result__ = await SpacetimeDB.Main.wait_for_reducer_response(__id__)
	cb.call(__result__)

## 0. message: MainMessage [br]
static func test_struct(message: MainMessage, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> void:
	var __id__: int = SpacetimeDB.Main.call_reducer('test_struct', [message], [&'MainMessage'])
	var __result__ = await SpacetimeDB.Main.wait_for_reducer_response(__id__)
	cb.call(__result__)