# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name SpacetimeAutoload extends Node

var Main: MainModuleClient

func _init() -> void:
	Main = preload('res://spacetime_bindings/schema/module_main_client.gd').new()
	add_child(Main)
