# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainTestPrivateScheduledCountScheduledIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, MainTestScheduledTable] = {}

func _init(p_local_db: LocalDatabase) -> void:
	set_meta("table_name", "test_private_scheduled_count")
	set_meta("field_name", "scheduled_id")
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: int) -> MainTestScheduledTable:
	return _cache.get(col_val, null)
