# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainTestPublicScheduledCountTable extends _ModuleTable

var scheduled_id: MainTestPublicScheduledCountScheduledIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "test_public_scheduled_count")
	scheduled_id = MainTestPublicScheduledCountScheduledIdUniqueIndex.new(p_local_db)

func iter() -> Array[MainTestScheduledTable]:
	var rows: Array = super()
	var typed_array: Array[MainTestScheduledTable] = []
	typed_array.assign(rows)
	return typed_array
