# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainUserDataTable extends _ModuleTable

var identity: MainUserDataIdentityUniqueIndex
var name: MainUserDataNameUniqueIndex

func _init(db: LocalDatabase) -> void:
	super(db)
	set_meta("table_name", "user_data")
	identity = MainUserDataIdentityUniqueIndex.new(db)
	name = MainUserDataNameUniqueIndex.new(db)

func iter() -> Array[MainUserData]:
	var rows: Array = super()
	var typed_array: Array[MainUserData] = []
	typed_array.assign(rows)
	return typed_array
