# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainUserNextIdentityUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, MainUser] = {}

func _init(db: LocalDatabase) -> void:
	set_meta("table_name", "user_next")
	set_meta("field_name", "identity")
	_connect_cache_to_db(_cache, db)

func find(col_val: PackedByteArray) -> MainUser:
	return _cache.get(col_val, null)
