# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainLobbyTable extends _ModuleTable

var id: MainLobbyIdUniqueIndex

func _init(db: LocalDatabase) -> void:
	super(db)
	set_meta("table_name", "lobby")
	id = MainLobbyIdUniqueIndex.new(db)

func iter() -> Array[MainLobby]:
	var rows: Array = super()
	var typed_array: Array[MainLobby] = []
	typed_array.assign(rows)
	return typed_array
