# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainUserNextTable extends _ModuleTable

var identity: MainUserNextIdentityUniqueIndex

func _init(db: LocalDatabase) -> void:
	super(db)
	set_meta("table_name", "user_next")
	identity = MainUserNextIdentityUniqueIndex.new(db)

func iter() -> Array[MainUser]:
	var rows: Array = super()
	var typed_array: Array[MainUser] = []
	typed_array.assign(rows)
	return typed_array
