# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainUserTable extends _ModuleTable

var identity: MainUserIdentityUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "user")
	identity = MainUserIdentityUniqueIndex.new(p_local_db)

func iter() -> Array[MainUser]:
	var rows: Array = super()
	var typed_array: Array[MainUser] = []
	typed_array.assign(rows)
	return typed_array
