# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainLobbyIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, MainLobby] = {}

func _init(db: LocalDatabase) -> void:
	set_meta("table_name", "lobby")
	set_meta("field_name", "id")
	_connect_cache_to_db(_cache, db)

func find(col_val: int) -> MainLobby:
	return _cache.get(col_val, null)
