# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainUserDataNameUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[String, MainUserData] = {}

func _init(db: LocalDatabase) -> void:
	set_meta("table_name", "user_data")
	set_meta("field_name", "name")
	_connect_cache_to_db(_cache, db)

func find(col_val: String) -> MainUserData:
	return _cache.get(col_val, null)
