# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainDamage extends Resource

const module_name := "Main"
@export var amount: int 
@export var source: PackedByteArray 
@export var int_vec: Array[int] 

func _init() -> void:
	set_meta('bsatn_type_amount', &'u32')
	set_meta('bsatn_type_source', &'identity')
	set_meta('bsatn_type_int_vec', &'u8')

## 0. amount: int[br]
## 1. source: PackedByteArray[br]
## 2. int_vec: Array of int[br]
static func create(_amount: int, _source: PackedByteArray, _int_vec: Array[int]) -> MainDamage:
	var result = MainDamage.new()
	result.amount = _amount
	result.source = _source
	result.int_vec = _int_vec
	return result
