# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainUser extends _ModuleTableType

const module_name := "Main"
const table_names: Array[String] = ['user', 'user_next']

@export var identity: PackedByteArray 
@export var online: bool 
@export var lobby_id: int 
@export var damage: MainDamage 
@export var test_option_string: Option ## Option of Array of String
@export var test_option_message: Option ## Option of MainMessage

func _init() -> void:
	set_meta('primary_key', 'identity')
	set_meta('bsatn_type_identity', &'identity')
	set_meta('bsatn_type_online', &'bool')
	set_meta('bsatn_type_lobby_id', &'u64')
	set_meta('bsatn_type_damage', &'MainDamage')
	set_meta('bsatn_type_test_option_string', &'vec_string')
	set_meta('bsatn_type_test_option_message', &'MainMessage')

## 0. identity: PackedByteArray[br]
## 1. online: bool[br]
## 2. lobby_id: int[br]
## 3. damage: MainDamage[br]
## 4. test_option_string: Option of Array of String[br]
## 5. test_option_message: Option of MainMessage[br]
static func create(_identity: PackedByteArray, _online: bool, _lobby_id: int, _damage: MainDamage, _test_option_string: Option, _test_option_message: Option) -> MainUser:
	var result = MainUser.new()
	result.identity = _identity
	result.online = _online
	result.lobby_id = _lobby_id
	result.damage = _damage
	result.test_option_string = _test_option_string
	result.test_option_message = _test_option_message
	return result
