# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainMessage extends Resource

@export var int_value: int 
@export var string_value: String 
@export var int_vec: Array[int] 
@export var string_vec: Array[String] 
@export var test_option: Option ## Option of String
@export var test_option_vec: Option ## Option of Array of String
@export var test_inner: Option ## Option of MainDamage

func _init() -> void:
	set_meta('bsatn_type_int_value', &'u8')
	set_meta('bsatn_type_string_value', &'string')
	set_meta('bsatn_type_int_vec', &'u8')
	set_meta('bsatn_type_string_vec', &'string')
	set_meta('bsatn_type_test_option', &'string')
	set_meta('bsatn_type_test_option_vec', &'vec_string')
	set_meta('bsatn_type_test_inner', &'MainDamage')

## 0. int_value: int[br]
## 1. string_value: String[br]
## 2. int_vec: Array of int[br]
## 3. string_vec: Array of String[br]
## 4. test_option: Option of String[br]
## 5. test_option_vec: Option of Array of String[br]
## 6. test_inner: Option of MainDamage[br]
static func create(p_int_value: int, p_string_value: String, p_int_vec: Array[int], p_string_vec: Array[String], p_test_option: Option, p_test_option_vec: Option, p_test_inner: Option) -> MainMessage:
	var result = MainMessage.new()
	result.int_value = p_int_value
	result.string_value = p_string_value
	result.int_vec = p_int_vec
	result.string_vec = p_string_vec
	result.test_option = p_test_option
	result.test_option_vec = p_test_option_vec
	result.test_inner = p_test_inner
	return result
