# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainUser extends _ModuleTableType

const module_name := "Main"
const table_names: Array[String] = ['user', 'user_next']

@export var identity: PackedByteArray 
@export var online: bool 
@export var lobby_id: int 
@export var damage: MainDamage 
@export var test_option_string: Option ## Option of Array of String
@export var test_option_message: Option ## Option of MainMessage

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'identity')
	set_meta('bsatn_type_identity', &'identity')
	set_meta('bsatn_type_online', &'bool')
	set_meta('bsatn_type_lobby_id', &'u64')
	set_meta('bsatn_type_damage', &'MainDamage')
	set_meta('bsatn_type_test_option_string', &'vec_string')
	set_meta('bsatn_type_test_option_message', &'MainMessage')

## 0. identity: PackedByteArray[br]
## 1. online: bool[br]
## 2. lobby_id: int[br]
## 3. damage: MainDamage[br]
## 4. test_option_string: Option of Array of String[br]
## 5. test_option_message: Option of MainMessage[br]
static func create(p_identity: PackedByteArray, p_online: bool, p_lobby_id: int, p_damage: MainDamage, p_test_option_string: Option, p_test_option_message: Option) -> MainUser:
	var result: MainUser = MainUser.new()
	result.identity = p_identity
	result.online = p_online
	result.lobby_id = p_lobby_id
	result.damage = p_damage
	result.test_option_string = p_test_option_string
	result.test_option_message = p_test_option_message
	return result
