# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainDamage extends Resource

@export var amount: int 
@export var source: PackedByteArray 
@export var int_vec: Array[int] 

func _init() -> void:
	set_meta('bsatn_type_amount', &'u32')
	set_meta('bsatn_type_source', &'identity')
	set_meta('bsatn_type_int_vec', &'u8')

## 0. amount: int[br]
## 1. source: PackedByteArray[br]
## 2. int_vec: Array of int[br]
static func create(p_amount: int, p_source: PackedByteArray, p_int_vec: Array[int]) -> MainDamage:
	var result = MainDamage.new()
	result.amount = p_amount
	result.source = p_source
	result.int_vec = p_int_vec
	return result
