# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainTestType extends Resource

@export var test_name: String 
@export var test_int: int 

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key in get_meta_list():
		set_meta(key, null)

	set_meta('bsatn_type_test_name', &'string')
	set_meta('bsatn_type_test_int', &'u64')

## 0. test_name: String[br]
## 1. test_int: int[br]
static func create(p_test_name: String, p_test_int: int) -> MainTestType:
	var result: MainTestType = MainTestType.new()
	result.test_name = p_test_name
	result.test_int = p_test_int
	return result
